apiVersion: v1
kind: Service
metadata:
  name: catalogo-service
spec:
  selector:
    app: catalogo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
    nodePort: 30083
  type: LoadBalancer

