name: CI - Testes e Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

env:
  DOCKER_CATALOGO_IMAGE: mldev7/catalogo-service
  DOTNET_VERSION: '8.0.x'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Testes e Validação
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependências
      run: dotnet restore

    - name: Build projeto
      run: dotnet build --no-restore --configuration Release

    - name: Executar testes
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Localizar arquivo de cobertura
      id: find_coverage
      run: |
        FILE=$(find . -name "coverage.cobertura.xml" | head -n 1)
        echo "Arquivo encontrado: $FILE"
        echo "coveragefile=$FILE" >> $GITHUB_OUTPUT

    - name: Instalar ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Gerar relatório de cobertura
      run: |
        reportgenerator \
          -reports:"${{ steps.find_coverage.outputs.coveragefile }}" \
          -targetdir:"coveragereport" \
          -assemblyfilters:"+Catalogo.Application" \
          -classfilters:"+Catalogo.Application.UseCases*" \
          -reporttypes:"TextSummary"

    - name: Mostrar % de Coverage no log
      run: |
        echo "---- Resultado da cobertura ----"
        cat coveragereport/Summary.txt

        COVERAGE=$(grep -oP 'Line coverage:\s+\K[0-9]+' coveragereport/Summary.txt)
        echo "Cobertura de linhas: $COVERAGE%"

  sonar:
    runs-on: windows-latest
    name: SonarCloud

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Sonar begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin `
            /k:"burguer404_Burguer404-Catalogo-MicroServico" `
            /o:"burguer404-1" `
            /d:sonar.cs.cobertura.reportsPaths="**/coverage.cobertura.xml" `
            /d:sonar.qualitygate.wait=true

      - name: Test with coverage
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Sonar end
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end


  build-and-push:
    name: Build e Push Docker
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_CATALOGO_IMAGE }}:${{ github.sha }}
          ${{ env.DOCKER_CATALOGO_IMAGE }}:latest
        cache-from: type=registry,ref=${{ env.DOCKER_CATALOGO_IMAGE }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_CATALOGO_IMAGE }}:buildcache,mode=max

